sts_gaming_group_kafka:
  consumers:
    instances:
      App\Consumers\CharConsumer:
        brokers: [ 'kafka:19092' ]
        schema_registry: 'http://localhost:8081'
        group_id: 'char-consumer'
        topics: [ 'char-topic' ]
        max_retries: 3 # defaults to 0 which means it is disabled
        max_retry_delay: 2500 # defaults to 2000 ms
        retry_delay: 300 # defaults to 200 ms
        retry_multiplier: 3 # defaults to 2
  producers:
    instances:
      App\Producers\CharProducer:
        brokers: [ 'kafka:19092' ]
        producer_topic: 'char-topic'