sts_gaming_group_kafka:
  consumers:
    instances:
      App\Consumers\CharConsumer:
        brokers: [ 'kafka:19092' ]
        group_id: 'char_consumer'
        topics: [ 'char-topic' ]
        register_missing_schemas: true
        register_missing_subjects: true
      App\Consumers\JsonConsumer:
        brokers: [ 'kafka:19092' ]
        group_id: 'json_consumer'
        topics: [ 'json-topic' ]
        register_missing_schemas: true
        register_missing_subjects: true

  producers:
    instances:
      App\Producers\CharProducer:
        brokers: [ 'kafka:19092' ]
        producer_topic: 'char-topic'
      App\Producers\JsonProducer:
        brokers: [ 'kafka:19092' ]
        producer_topic: 'json-topic'
      App\Producers\ObjectProducer:
        brokers: [ 'kafka:19092' ]
        producer_topic: 'object-topic'