<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ3MYQA1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ3MYQA1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ3MYQA1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ3MYQA1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ3MYQA1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z3MYQA1',
    'container.build_id' => '9ee36580',
    'container.build_time' => 1700924571,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ3MYQA1');
